### ISSUE TITLE
Repo not available for me to install ruby

### ISSUE THREAD

**Issue by thebeardedgeek** [AndreaRibuoli/RIBY#1]
I added the repo to my chroot "container" but it is no longer available:
![image](https://user-images.githubusercontent.com/9466407/187492657-3b091f0c-b550-4a92-9599-fc6109225f71.png)

![image](https://user-images.githubusercontent.com/9466407/187492766-21e9c2df-29f8-460a-ad1a-80a070c5a140.png)

**Comment by AndreaRibuoli** [comment]
Strange, it is active for me:

```
bash-5.1$ yum repolist all
id repo                                      nome repo                                    stato
andrearibuoli                                andrearibuoli                                abilitato:    14
ibm                                          ibm                                          abilitato: 1.002
ibmi-base                                    IBM i base                                   abilitato: 1.065
ibmi-release                                 IBM i 7.3                                    abilitato:    67
repolist: 2.148
```

Try again once Mozilla's certificates are installed (the certificates need to be installed in the **chroot** too):

```
yum install ca-certificates-mozilla
```

( *https://www.andrearibuoli.it/pase/* is correctly forbidden )

**Comment by thebeardedgeek** [comment]
The Mozilla certificates are installed
![image](https://user-images.githubusercontent.com/9466407/187544465-b6d2b006-23a5-49ff-b347-95de03254ef7.png)

I wonder if there is another way to test it.

**Comment by AndreaRibuoli** [comment]
Can you ssh **to your chroot** and once there perform the `yum repolist all`?
You should be allowed to access [my repomd](https://www.andrearibuoli.it/pase/repodata/repomd.xml), too.

**Comment by thebeardedgeek** [comment]
This is outside the chroot `yum repolist all`
![image](https://user-images.githubusercontent.com/9466407/187548383-a3367695-a01d-4ace-ba70-4ea9add66a14.png)

This is inside the chroot `yum repolist all`
![image](https://user-images.githubusercontent.com/9466407/187548471-e5d8f09b-0e2e-4d13-bbbd-a1886553e360.png)

**Comment by AndreaRibuoli** [comment]
Now please perform the following command from *inside* chroot:

`yum list | grep cert`

**Comment by AndreaRibuoli** [comment]
Consider that you can manage the status with: 

```
yum-config-manager --enable andrearibuoli
```

```
yum-config-manager --disable andrearibuoli
```

**Comment by thebeardedgeek** [comment]
I ran the command to enable the repo but it was already enabled. It still shows disabled when I do a `yum repolist all`

This is a new LPAR with 7.4 and PTFs installed. I just recently installed the open source environment and then started running through you Ruby readme. Maybe I am missing something else to be able to access your repo? I was able to run `git clone https://github.com/AndreaRibuoli/RIBY.git` without issue and I can hit the IBM OSS repos fine...weird.

bash-5.1$ yum-config-manager --enable andrearibuoli
================================== repo: andrearibuoli ==================================
[andrearibuoli]
bandwidth = 0
base_persistdir = /QOpenSys/var/lib/yum/repos/ppc/7.4
baseurl = https://www.andrearibuoli.it/pase
cache = 0
cachedir = /QOpenSys/var/cache/yum/andrearibuoli
cost = 1000
enabled = 1
enablegroups = True
exclude =
failovermethod = roundrobin
gpgcadir = /QOpenSys/var/lib/yum/repos/ppc/7.4/andrearibuoli/gpgcadir
gpgcakey =
gpgcheck = False
gpgdir = /QOpenSys/var/lib/yum/repos/ppc/7.4/andrearibuoli/gpgdir
gpgkey =
hdrdir = /QOpenSys/var/cache/yum/andrearibuoli/headers
http_caching = all
includepkgs =
keepalive = True
mdpolicy = group:primary
mediaid =
metadata_expire = 21600
metalink =
mirrorlist =
mirrorlist_expire = 86400
name = andrearibuoli
password =
persistdir = /QOpenSys/var/lib/yum/repos/ppc/7.4/andrearibuoli
pkgdir = /QOpenSys/var/cache/yum/andrearibuoli/packages
proxy =
proxy_dict =
proxy_password =
proxy_username =
repo_gpgcheck = False
retries = 10
skip_if_unavailable = True
sslcacert =
sslclientcert =
sslclientkey =
sslverify = True
throttle = 0
timeout = 30.0
username =

**Comment by thebeardedgeek** [comment]
I tried this just to see the output but I keep getting 443: Connection refused
![image](https://user-images.githubusercontent.com/9466407/187574141-367a280b-6a46-4c95-aa88-025692948ddf.png)

**Comment by AndreaRibuoli** [comment]
Possibly a side effect of the very recent changes introduced by IBM:

see [Jesse's article](https://techchannel.com/Trends/08/2022/ibm-i-rpm-repositories)

I will investigate the issue.

**Comment by ThePrez** [comment]
Given some of @thebeardedgeek's previous adventures, I believe the curl error is legitimate. The network is not allowing outbound https connections. 

@AndreaRibuoli do you by chance have http also?

**Comment by ThePrez** [comment]
Try this command to verify connectivity to the https port:
```
/QOpenSys/pkgs/bin/python2.7 -c "import socket; socket.create_connection(('andrearibuoli.it', 443), 30); print 'success'"
```

**Comment by AndreaRibuoli** [comment]
@ThePrez, thank you for your prompt help! 

@thebeardedgeek, I can confirm you that:

- nor the latest IBM updates 
- nor IBM i 7.4 

are a problem to access my repository.
This is what I get on an IBM i 7.4:

```
bash-5.1$ yum repolist all
andrearibuoli                                               | 2.9 kB  00:00     
andrearibuoli/primary_db                                    |  26 kB  00:00     
repo id                          repo name                         status
andrearibuoli                    andrearibuoli                     enabled:   14
ibm                              ibm                               enabled: 1002
ibmi-base                        IBM i base                        enabled: 1002
ibmi-release                     IBM i 7.4                         enabled:   67
repolist: 2085
``` 

If you agree (reply to one of the emails I have sent you) I can pass you the RPMs as an email attachment. 
You can then perform a local install inside your chroot.

Best Regards,

   Andrea

**Comment by thebeardedgeek** [comment]
I was able to resolve the issue on my end. Sorry for all the confusion but thanks for the learning experience. I can't see anything as far as the firewall configuration and when we looked at this system there was some confusion. It is resolved and I can hit the repo now.

**Comment by AndreaRibuoli** [comment]
Should you not appreciate my build of Ruby for PASE on IBM i... at least you solved your firewall issue! Well done!

**Comment by thebeardedgeek** [comment]
I definitely will appreciate this build and I have been waiting for it for awhile now. Thank you!
